// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7k3jc-wpp68kVqKQ94JaO2EC9VIs1gqU',
    appId: '1:852579635594:web:9ac92d2f6cc59e487e7873',
    messagingSenderId: '852579635594',
    projectId: 'sanh-9a3b8',
    authDomain: 'sanh-9a3b8.firebaseapp.com',
    databaseURL: 'https://sanh-9a3b8-default-rtdb.firebaseio.com',
    storageBucket: 'sanh-9a3b8.firebasestorage.app',
    measurementId: 'G-26EZ1ZBTM9',
    // apiKey: "AIzaSyDTnMcQtsrjwMOhFbyX0FXbPFnQCl0nOMI",
    // authDomain: "todo-48d54.firebaseapp.com",
    // projectId: "todo-48d54",
    // storageBucket: "todo-48d54.firebasestorage.app",
    // messagingSenderId: "415780624547",
    // appId: "1:415780624547:web:1e2eca212bd18cfddc8716",
    // measurementId: "G-7LSYWVQLMP",
  );
}
